### ISSUE TITLE
Can't use disable-scroll with SSR

### ISSUE THREAD

**Issue by mciastek** [gilbarbara/disable-scroll#11]
I see `scrollingelement` polyfill is not prepared to work in SSR environment. When I'm trying to use it with SSR I get:
```
if (!('scrollingElement' in document)) (function() {
                            ^
ReferenceError: document is not defined
```

So unfortunately [canUseDOM](https://github.com/gilbarbara/disable-scroll/blob/master/src/index.js#L3-L7) is useless for SSR. I'm aware that `scrollingelement` as a polyfill don't support SSR. This means that you need to use this polyfill when disable-scroll isn't in SSR environment.

**Comment by gilbarbara** [comment]
Which canUseDom implementation are you using?

Anyway, this is a DOM module and I don't think it should be aware of SSR.

**Comment by gilbarbara** [comment]
Nevermind..
I'll take a look soon

**Comment by Stosiu** [comment]
@gilbarbara any update on this?

**Comment by gilbarbara** [comment]
@Stosiu nope. Feel free to submit a PR
