### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by andret2344** [gilbarbara/disable-scroll#19]
When using library in Typescript, I have to add my own types:
```TypeScript
declare module 'disable-scroll' {
	export interface DisableScrollOptions {
		disableWheel: boolean;
		disableScroll: boolean;
		disableKeys: boolean;
		keyboardKeys: number[];
		authorizedInInputs: number[];
	}

	export function on(element?: HTMLElement, options?: DisableScrollOptions): void;
	export function off(): void;
}
```
How about adding them as `@types/disable-scroll` library?

**Comment by gilbarbara** [comment]
Hey!

I think it's great. Do you want to add it there?

**Comment by andret2344** [comment]
To be honest I have never done it before, I'm not a module developer. I'd need some help to do it on my own

**Comment by gilbarbara** [comment]
Added in 0.6.0. Thanks
