### ISSUE TITLE
Warning: event not passive

### ISSUE THREAD

**Issue by mileung** [gilbarbara/disable-scroll#2]
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

But I guess this has to happen because this package uses preventDefault, but [a passive listener would ignore that](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#solution-the-passive-option)

**Comment by gilbarbara** [comment]
Yeah, I can't have passive listeners since the goal of this package is to disable that...
