### ISSUE TITLE
authorizedInInputs not working

### ISSUE THREAD

**Issue by JesseZomer** [gilbarbara/disable-scroll#20]
Hello,

The default authorizedInInputs (is the extra 'In' a typo?) are not working. This is because of this piece of code:
```javascript
    if (['INPUT', 'TEXTAREA'].includes(e.target.tagName)) {
      keys = this.options.authorizedInInputs;
    }
```
Here you're setting the keys that you should be allowed to press when in a input field to the keys you're not allowed to press. It should be keys = keys - authinputs.

I'm using the workaround of just enabling these keys, but would be nice if you could publish a fix

Thanks

**Comment by gilbarbara** [comment]
Fixed in 0.6.0
