### ISSUE TITLE
There doesn't seem to be support for the standard scrollbar(disable the scrollbar as well) 

### ISSUE THREAD

**Issue by aditya-rastogi23** [gilbarbara/disable-scroll#26]
I am using react scroll to scroll via code and want user scroll to be completely disabled but programmatically scrolling should be allowed. I tried to use scrollbar width(set at 0) to disable scrolling and this works fine but I want to have the scrollbar enabled on some pages and disabled on others. This could be added as a possible enhancement maybe? I am not sure if it's possible.

**Comment by gilbarbara** [comment]
hey @aditya-rastogi23 

This is a very simple library to completely disable scrolling. There are no plans to change the API.
You can use CSS to disable scrolling in some contexts while scrolling in others.
